### ISSUE TITLE
A liitle problem

### ISSUE THREAD

**Issue by FoxEast2021** [jandrassy/WiFiEspAT#44]
Hi sir
Does your library support the (  client.setNoDelay(true);  ) command?
Because when compiling it gave the following error!
Error :
`'class WiFiClient' has no member named 'setNoDelay'
`

**Comment by jandrassy** [comment]
> Hi sir
> Does your library support the ( client.setNoDelay(true); ) command?
> Because when compiling it gave the following error!
> Error :
> `'class WiFiClient' has no member named 'setNoDelay' `

AT firmware doesn't support it.
it is the setting to turn off TCP Nagle's algoritm. AT firmware doesn't allow to turn it off.
it wouldn't make much sense, because we first transfer data over Serial to the ESP and then the AT firmware sends it over WiFi. Without Nagle's algorihm single bytes received over Serial would be sent in a TCP packet over WiFi.
