### ISSUE TITLE
Missing API methods

### ISSUE THREAD

**Issue by guilhermeaiolfi** [jandrassy/WiFiEspAT#62]
Hi,

sorry if the question is somehow dumb, I've just started playing around in the arduino world. What I'm trying to do is to use the https://github.com/skaarj1989/mWebSockets library using WiFiEsp. I would be willing to implement what is need in the mWebSocket side for it to work. But as I scanned the code, there are some missing API, like ```hasClient()```.

What would it be the equivalent of that method in WiFiEspAT? Is that even make any sense? Any guidance would welcome.

Thanks.

**Comment by jandrassy** [comment]
`hasClient()` is from esp8266 WiFi library, because of misunderstanding of the original Arduino WiFi API for `available()`.
In Arduino WiFi API you can check `available()` and you don't have to process the returnd client. In esp8266 WiFi library `available()` behaves as Arduino API recent addition `accept()` in Ethernet library.
https://www.arduino.cc/en/Reference/WiFiServerAvailable
https://www.arduino.cc/en/Reference/EthernetServerAccept
